### ISSUE TITLE
change the language of the outpup.

### ISSUE THREAD

**Issue by prietus** [SpiderDave/spidey-supybot-plugins#4]
tmdb has several languages available, I wonder if I can set the plugin to pick the info in other language than english, spanish in my case, since the web site has all the info (movies tv etc.) in spanish I wonder where can I specify such option.
thanks in advance.

**Comment by SpiderDave** [comment]
I've added a language option to commands, for example:
&movie --language fr the matrix

The option works for the person command too, though those pages aren't available in other languages.  It's still useful as the links lead to translated pages.

There is currently no configuration option to set a default language, so make an alias if need.

**Comment by prietus** [comment]
thanks! it works perfect. I just had to fix since i do python3.
try:
    import urllib.request as urllib2
except ImportError:
    import urllib2

thanks a lot.

**Comment by SpiderDave** [comment]
Added the python 3 fix, thanks.
